
package com.msrm.webservice.example2.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://example2.webservice.msrm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.AddResponse")
    @Action(input = "http://example2.webservice.msrm.com/PersonService/addRequest", output = "http://example2.webservice.msrm.com/PersonService/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.UpdateResponse")
    @Action(input = "http://example2.webservice.msrm.com/PersonService/updateRequest", output = "http://example2.webservice.msrm.com/PersonService/updateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.DeleteResponse")
    @Action(input = "http://example2.webservice.msrm.com/PersonService/deleteRequest", output = "http://example2.webservice.msrm.com/PersonService/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.msrm.webservice.example2.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPerson", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.GetAllPerson")
    @ResponseWrapper(localName = "getAllPersonResponse", targetNamespace = "http://example2.webservice.msrm.com/", className = "com.msrm.webservice.example2.GetAllPersonResponse")
    @Action(input = "http://example2.webservice.msrm.com/PersonService/getAllPersonRequest", output = "http://example2.webservice.msrm.com/PersonService/getAllPersonResponse")
    public List<Person> getAllPerson();

}
